### ISSUE TITLE
Dependency on jogamp.opencl unclear

### ISSUE THREAD

**Issue by queisser** [AbFab3D/AbFab3D#7]
Running "ant build" gives me this error (Win 7 x64)
[javac] AbFab3D\src\java\abfab3d\opencl\OpenCLResource.java:14: package com.jogamp.opencl does not exist

.. and a bunch of follow-on errors that would go away if I could resolve the reference.

I tried installing jogamp.opencl according to their instructions but the ant build doesn't seem to pick up the jar file. For casual java uses like myself it would be great to document how to set up opencl for abfab3d.

Thanks,
Andrew

**Comment by giles7777** [comment]
Now fixed.
